export interface CountryFact {
    capital: string;
    languages: string[];
    colonizedBy: string | null;
    timeline: { year: string; event: string }[];
    population?: number;
    region?: string;
    subregion?: string;
    currencies?: { name: string; symbol: string }[];
    flagPng?: string;
  }
   
  // REST Countries API — free, no key
  const API_BASE = "https://restcountries.com/v3.1";
   
  // Cache fetched results
  const cache = new Map<string, CountryFact>();
   
  // Name mapping: Natural Earth names → REST Countries names
  const NAME_MAP: Record<string, string> = {
    "United States of America": "United States",
    "Dem. Rep. Congo": "DR Congo",
    "Central African Rep.": "Central African Republic",
    "S. Sudan": "South Sudan",
    "Côte d'Ivoire": "Ivory Coast",
    "Bosnia and Herz.": "Bosnia and Herzegovina",
    "Dominican Rep.": "Dominican Republic",
    "Eq. Guinea": "Equatorial Guinea",
    "eSwatini": "Eswatini",
    "Solomon Is.": "Solomon Islands",
    "W. Sahara": "Western Sahara",
    "N. Cyprus": "Cyprus",
    "Somaliland": "Somalia",
    "Fr. S. Antarctic Lands": "French Southern Territories",
    "Czechia": "Czech Republic",
    "North Macedonia": "North Macedonia",
  };
   
  export async function fetchCountryFacts(name: string): Promise<CountryFact | null> {
    if (cache.has(name)) return cache.get(name)!;
   
    const searchName = NAME_MAP[name] || name;
   
    try {
      const res = await fetch(
        `${API_BASE}/name/${encodeURIComponent(searchName)}?fields=name,capital,languages,population,region,subregion,currencies,flags`
      );
      if (!res.ok) return getFallback(name);
   
      const data = await res.json();
      const country = Array.isArray(data) ? data[0] : data;
   
      const languages = country.languages
        ? Object.values(country.languages) as string[]
        : [];
   
      const currencies = country.currencies
        ? Object.values(country.currencies).map((c: unknown) => {
            const cur = c as { name?: string; symbol?: string };
            return { name: cur.name || "", symbol: cur.symbol || "" };
          })
        : [];
   
      const flagPng = country.flags?.png || undefined;
   
      const fact: CountryFact = {
        capital: country.capital?.[0] || "Unknown",
        languages,
        population: country.population,
        region: country.region,
        subregion: country.subregion,
        currencies,
        flagPng,
        colonizedBy: COLONIAL_HISTORY[name] || null,
        timeline: TIMELINES[name] || [],
      };
   
      cache.set(name, fact);
      return fact;
    } catch {
      return getFallback(name);
    }
  }
   
  function getFallback(name: string): CountryFact | null {
    const colonial = COLONIAL_HISTORY[name] || null;
    const timeline = TIMELINES[name] || [];
    if (!timeline.length) return null;
    return { capital: "—", languages: [], colonizedBy: colonial, timeline };
  }
  
  const COLONIAL_HISTORY: Record<string, string> = {
    "Algeria": "France",
    "Angola": "Portugal",
    "Australia": "Britain",
    "Bahamas": "Britain",
    "Bahrain": "Britain",
    "Bangladesh": "Britain",
    "Barbados": "Britain",
    "Belize": "Britain",
    "Benin": "France",
    "Bolivia": "Spain",
    "Botswana": "Britain",
    "Brazil": "Portugal",
    "Brunei": "Britain",
    "Burkina Faso": "France",
    "Burundi": "Belgium",
    "Cambodia": "France",
    "Cameroon": "Germany, France",
    "Canada": "Britain, France",
    "Cape Verde": "Portugal",
    "Central African Rep.": "France",
    "Chad": "France",
    "Chile": "Spain",
    "Colombia": "Spain",
    "Comoros": "France",
    "Congo": "France",
    "Costa Rica": "Spain",
    "Côte d'Ivoire": "France",
    "Cuba": "Spain",
    "Cyprus": "Britain",
    "Dem. Rep. Congo": "Belgium",
    "Djibouti": "France",
    "Dominican Rep.": "Spain",
    "Ecuador": "Spain",
    "Egypt": "Britain",
    "El Salvador": "Spain",
    "Eq. Guinea": "Spain",
    "Eritrea": "Italy",
    "eSwatini": "Britain",
    "Fiji": "Britain",
    "Gabon": "France",
    "Gambia": "Britain",
    "Ghana": "Britain",
    "Grenada": "Britain",
    "Guatemala": "Spain",
    "Guinea": "France",
    "Guinea-Bissau": "Portugal",
    "Guyana": "Britain",
    "Haiti": "France",
    "Honduras": "Spain",
    "Hong Kong": "Britain",
    "India": "Britain",
    "Indonesia": "Netherlands",
    "Iraq": "Britain",
    "Israel": "Britain",
    "Jamaica": "Britain",
    "Jordan": "Britain",
    "Kenya": "Britain",
    "Kuwait": "Britain",
    "Laos": "France",
    "Lebanon": "France",
    "Lesotho": "Britain",
    "Liberia": "United States",
    "Libya": "Italy",
    "Madagascar": "France",
    "Malawi": "Britain",
    "Malaysia": "Britain",
    "Maldives": "Britain",
    "Mali": "France",
    "Malta": "Britain",
    "Mauritania": "France",
    "Mauritius": "Britain",
    "Mexico": "Spain",
    "Morocco": "France, Spain",
    "Mozambique": "Portugal",
    "Myanmar": "Britain",
    "Namibia": "Germany, South Africa",
    "New Zealand": "Britain",
    "Nicaragua": "Spain",
    "Niger": "France",
    "Nigeria": "Britain",
    "North Korea": "Japan",
    "Oman": "Portugal (partial)",
    "Pakistan": "Britain",
    "Palestine": "Britain",
    "Panama": "Spain",
    "Papua New Guinea": "Australia, Britain",
    "Paraguay": "Spain",
    "Peru": "Spain",
    "Philippines": "Spain, United States",
    "Qatar": "Britain",
    "Rwanda": "Belgium",
    "São Tomé and Príncipe": "Portugal",
    "Senegal": "France",
    "Seychelles": "Britain",
    "Sierra Leone": "Britain",
    "Singapore": "Britain",
    "Solomon Is.": "Britain",
    "Somalia": "Italy, Britain",
    "South Africa": "Netherlands, Britain",
    "South Korea": "Japan",
    "Sri Lanka": "Britain",
    "Sudan": "Britain, Egypt",
    "Suriname": "Netherlands",
    "Syria": "France",
    "Taiwan": "Japan",
    "Tanzania": "Germany, Britain",
    "Timor-Leste": "Portugal",
    "Togo": "Germany, France",
    "Tonga": "Britain",
    "Trinidad and Tobago": "Britain",
    "Tunisia": "France",
    "Uganda": "Britain",
    "United Arab Emirates": "Britain",
    "United States of America": "Britain",
    "Uruguay": "Spain",
    "Vanuatu": "France, Britain",
    "Venezuela": "Spain",
    "Vietnam": "France",
    "W. Sahara": "Spain",
    "Yemen": "Britain (South)",
    "Zambia": "Britain",
    "Zimbabwe": "Britain",
    "Argentina": "Spain",
    "S. Sudan": "Britain, Egypt",
  };
  
  const TIMELINES: Record<string, { year: string; event: string }[]> = {
    "Afghanistan": [
      { year: "1747", event: "Durrani Empire founded by Ahmad Shah" },
      { year: "1839", event: "First Anglo-Afghan War" },
      { year: "1878", event: "Second Anglo-Afghan War" },
      { year: "1919", event: "Independence from Britain (Third Anglo-Afghan War)" },
      { year: "1973", event: "Republic declared, monarchy overthrown" },
      { year: "1979", event: "Soviet invasion" },
      { year: "1989", event: "Soviet withdrawal" },
      { year: "1996", event: "Taliban seize Kabul" },
      { year: "2001", event: "US-led intervention" },
      { year: "2021", event: "Taliban regain power, US withdrawal" },
    ],
    "Albania": [
      { year: "1190", event: "Principality of Arbër (first Albanian state)" },
      { year: "1468", event: "Ottoman conquest after Skanderbeg's death" },
      { year: "1912", event: "Independence from Ottoman Empire" },
      { year: "1939", event: "Italian invasion and occupation" },
      { year: "1944", event: "Communist state under Enver Hoxha" },
      { year: "1967", event: "Declared world's first atheist state" },
      { year: "1991", event: "Democracy restored" },
      { year: "2009", event: "Joins NATO" },
    ],
    "Algeria": [
      { year: "1516", event: "Ottoman rule begins" },
      { year: "1830", event: "French colonization begins" },
      { year: "1847", event: "Abd el-Kader's resistance defeated" },
      { year: "1945", event: "Sétif and Guelma massacres" },
      { year: "1954", event: "Algerian War of Independence begins" },
      { year: "1962", event: "Independence from France" },
      { year: "1991", event: "Civil war (Black Decade) begins" },
      { year: "2002", event: "Civil war ends" },
      { year: "2019", event: "Hirak protest movement" },
    ],
    "Angola": [
      { year: "1575", event: "Portuguese colony established" },
      { year: "1641", event: "Dutch briefly seize Luanda" },
      { year: "1961", event: "War of independence begins" },
      { year: "1975", event: "Independence from Portugal" },
      { year: "1975", event: "Civil war begins (MPLA vs UNITA)" },
      { year: "1988", event: "Battle of Cuito Cuanavale" },
      { year: "2002", event: "Civil war ends" },
    ],
    "Argentina": [
      { year: "1536", event: "Spanish colonization (Buenos Aires founded)" },
      { year: "1810", event: "May Revolution" },
      { year: "1816", event: "Independence declared" },
      { year: "1865", event: "War of the Triple Alliance" },
      { year: "1946", event: "Perón era begins" },
      { year: "1976", event: "Military junta seizes power (Dirty War)" },
      { year: "1982", event: "Falklands/Malvinas War" },
      { year: "1983", event: "Democracy restored" },
      { year: "2001", event: "Economic crisis" },
    ],
    "Armenia": [
      { year: "301", event: "First nation to adopt Christianity" },
      { year: "1375", event: "Fall of Armenian Kingdom of Cilicia" },
      { year: "1915", event: "Armenian Genocide" },
      { year: "1918", event: "First Republic of Armenia" },
      { year: "1920", event: "Soviet annexation" },
      { year: "1991", event: "Independence from USSR" },
      { year: "1992", event: "Nagorno-Karabakh War begins" },
      { year: "2018", event: "Velvet Revolution" },
      { year: "2023", event: "Loss of Nagorno-Karabakh" },
    ],
    "Australia": [
      { year: "65000 BC", event: "Aboriginal habitation begins" },
      { year: "1770", event: "Cook claims east coast for Britain" },
      { year: "1788", event: "First Fleet arrives (British penal colony)" },
      { year: "1851", event: "Gold rush begins" },
      { year: "1901", event: "Federation (Commonwealth established)" },
      { year: "1915", event: "Gallipoli campaign (ANZAC)" },
      { year: "1942", event: "Bombing of Darwin (WWII)" },
      { year: "1967", event: "Indigenous rights referendum" },
      { year: "2008", event: "National apology to Stolen Generations" },
    ],
    "Austria": [
      { year: "1278", event: "Habsburg rule begins" },
      { year: "1529", event: "First Ottoman siege of Vienna" },
      { year: "1683", event: "Second Ottoman siege of Vienna" },
      { year: "1867", event: "Austro-Hungarian Empire formed" },
      { year: "1914", event: "Assassination of Franz Ferdinand triggers WWI" },
      { year: "1918", event: "Republic proclaimed, empire dissolved" },
      { year: "1938", event: "Anschluss (Nazi annexation)" },
      { year: "1945", event: "Allied liberation" },
      { year: "1955", event: "Sovereignty restored, permanent neutrality" },
      { year: "1995", event: "Joins EU" },
    ],
    "Azerbaijan": [
      { year: "1501", event: "Safavid dynasty rises" },
      { year: "1813", event: "Russian conquest (Treaty of Gulistan)" },
      { year: "1918", event: "First secular republic in Muslim world" },
      { year: "1920", event: "Soviet annexation" },
      { year: "1991", event: "Independence from USSR" },
      { year: "1992", event: "Nagorno-Karabakh War" },
      { year: "2020", event: "Second Nagorno-Karabakh War" },
      { year: "2023", event: "Recaptures Nagorno-Karabakh" },
    ],
    "Bangladesh": [
      { year: "1576", event: "Mughal conquest of Bengal" },
      { year: "1757", event: "Battle of Plassey (British East India Company)" },
      { year: "1943", event: "Bengal famine" },
      { year: "1947", event: "Part of Pakistan (East Pakistan)" },
      { year: "1971", event: "Liberation War, independence from Pakistan" },
      { year: "1974", event: "Famine" },
      { year: "1991", event: "Democracy restored" },
      { year: "2013", event: "Rana Plaza disaster" },
    ],
    "Belarus": [
      { year: "1569", event: "Part of Polish-Lithuanian Commonwealth" },
      { year: "1795", event: "Russian Empire annexation (Partitions of Poland)" },
      { year: "1919", event: "Belarusian SSR established" },
      { year: "1941", event: "Nazi occupation; massive civilian losses" },
      { year: "1986", event: "Chernobyl fallout affects Belarus heavily" },
      { year: "1991", event: "Independence from USSR" },
      { year: "1994", event: "Lukashenko elected" },
      { year: "2020", event: "Mass protests over disputed election" },
    ],
    "Belgium": [
      { year: "1302", event: "Battle of the Golden Spurs" },
      { year: "1830", event: "Independence from Netherlands" },
      { year: "1885", event: "Congo Free State under Leopold II" },
      { year: "1908", event: "Belgian Congo (state colony)" },
      { year: "1914", event: "German invasion (WWI)" },
      { year: "1940", event: "German invasion (WWII)" },
      { year: "1960", event: "Congo gains independence" },
      { year: "1993", event: "Federal state established" },
    ],
    "Benin": [
      { year: "1600", event: "Kingdom of Dahomey rises" },
      { year: "1724", event: "Dahomey becomes major slave trade state" },
      { year: "1894", event: "French conquest" },
      { year: "1960", event: "Independence from France" },
      { year: "1972", event: "Marxist-Leninist state" },
      { year: "1990", event: "Multi-party democracy (first in Africa)" },
    ],
    "Bhutan": [
      { year: "1616", event: "Zhabdrung Ngawang Namgyal unifies Bhutan" },
      { year: "1865", event: "Treaty of Sinchula with British India" },
      { year: "1907", event: "Monarchy established (Wangchuck dynasty)" },
      { year: "1971", event: "Joins United Nations" },
      { year: "2008", event: "Constitutional monarchy, first elections" },
    ],
    "Bolivia": [
      { year: "1438", event: "Inca conquest" },
      { year: "1538", event: "Spanish conquest" },
      { year: "1545", event: "Potosí silver mines (colonial exploitation)" },
      { year: "1825", event: "Independence (named after Bolívar)" },
      { year: "1879", event: "War of the Pacific (loses coast to Chile)" },
      { year: "1932", event: "Chaco War with Paraguay" },
      { year: "1952", event: "National Revolution" },
      { year: "2006", event: "Evo Morales elected (first Indigenous president)" },
    ],
    "Bosnia and Herz.": [
      { year: "1377", event: "Kingdom of Bosnia established" },
      { year: "1463", event: "Ottoman conquest" },
      { year: "1878", event: "Austro-Hungarian occupation" },
      { year: "1914", event: "Assassination of Franz Ferdinand in Sarajevo" },
      { year: "1945", event: "Part of Yugoslavia" },
      { year: "1992", event: "Independence declared; Bosnian War begins" },
      { year: "1995", event: "Srebrenica genocide; Dayton Agreement" },
    ],
    "Botswana": [
      { year: "1885", event: "British protectorate (Bechuanaland)" },
      { year: "1966", event: "Independence" },
      { year: "1967", event: "Diamonds discovered at Orapa" },
      { year: "1980", event: "Becomes Africa's fastest-growing economy" },
    ],
    "Brazil": [
      { year: "1500", event: "Portuguese arrival (Cabral)" },
      { year: "1549", event: "Colonial government established" },
      { year: "1695", event: "Destruction of Palmares (escaped slave state)" },
      { year: "1822", event: "Independence declared (Empire of Brazil)" },
      { year: "1888", event: "Slavery abolished (last in Americas)" },
      { year: "1889", event: "Republic proclaimed" },
      { year: "1930", event: "Vargas era begins" },
      { year: "1960", event: "Capital moved to Brasília" },
      { year: "1964", event: "Military dictatorship begins" },
      { year: "1985", event: "Democracy restored" },
    ],
    "Bulgaria": [
      { year: "681", event: "First Bulgarian Empire founded" },
      { year: "1018", event: "Byzantine conquest" },
      { year: "1185", event: "Second Bulgarian Empire" },
      { year: "1396", event: "Ottoman conquest" },
      { year: "1878", event: "Liberation (Russo-Turkish War)" },
      { year: "1912", event: "First Balkan War" },
      { year: "1944", event: "Soviet-backed communist takeover" },
      { year: "1989", event: "End of communism" },
      { year: "2007", event: "Joins EU" },
    ],
    "Burkina Faso": [
      { year: "1100", event: "Mossi Kingdoms established" },
      { year: "1896", event: "French conquest" },
      { year: "1960", event: "Independence from France" },
      { year: "1983", event: "Thomas Sankara revolution" },
      { year: "1987", event: "Sankara assassinated, Compaoré takes power" },
      { year: "2014", event: "Popular uprising ousts Compaoré" },
      { year: "2022", event: "Military coup" },
    ],
    "Burundi": [
      { year: "1680", event: "Kingdom of Burundi established" },
      { year: "1899", event: "German East Africa" },
      { year: "1916", event: "Belgian control" },
      { year: "1962", event: "Independence" },
      { year: "1972", event: "Mass killings" },
      { year: "1993", event: "Civil war begins" },
      { year: "2005", event: "End of civil war" },
    ],
    "Cambodia": [
      { year: "802", event: "Khmer Empire founded" },
      { year: "1113", event: "Angkor Wat constructed" },
      { year: "1431", event: "Fall of Angkor" },
      { year: "1863", event: "French protectorate" },
      { year: "1953", event: "Independence" },
      { year: "1970", event: "Coup; Khmer Republic; US bombing" },
      { year: "1975", event: "Khmer Rouge takes power; genocide begins" },
      { year: "1979", event: "Vietnamese invasion; Khmer Rouge falls" },
      { year: "1991", event: "Paris Peace Accords" },
    ],
    "Cameroon": [
      { year: "1472", event: "Portuguese arrive" },
      { year: "1884", event: "German colony (Kamerun)" },
      { year: "1916", event: "British and French take over (WWI)" },
      { year: "1960", event: "French Cameroon independent" },
      { year: "1961", event: "British Southern Cameroons joins" },
    ],
    "Canada": [
      { year: "1534", event: "Jacques Cartier explores for France" },
      { year: "1608", event: "Quebec City founded (New France)" },
      { year: "1763", event: "British control (Treaty of Paris)" },
      { year: "1812", event: "War of 1812" },
      { year: "1867", event: "Confederation (Dominion of Canada)" },
      { year: "1885", event: "Completion of transcontinental railway" },
      { year: "1914", event: "Enters WWI" },
      { year: "1939", event: "Enters WWII" },
      { year: "1982", event: "Constitution patriated (Charter of Rights)" },
    ],
    "Central African Rep.": [
      { year: "1889", event: "French colonization" },
      { year: "1960", event: "Independence" },
      { year: "1966", event: "Bokassa coup" },
      { year: "1976", event: "Bokassa declares himself emperor" },
      { year: "2013", event: "Civil conflict escalates" },
    ],
    "Chad": [
      { year: "900", event: "Kanem Empire" },
      { year: "1900", event: "French conquest" },
      { year: "1960", event: "Independence" },
      { year: "1965", event: "Civil war begins" },
      { year: "1990", event: "Idriss Déby takes power" },
      { year: "2021", event: "Déby killed; military council" },
    ],
    "Chile": [
      { year: "1541", event: "Spanish colonization (Santiago founded)" },
      { year: "1818", event: "Independence" },
      { year: "1879", event: "War of the Pacific (gains northern territory)" },
      { year: "1973", event: "Pinochet coup; Allende overthrown" },
      { year: "1990", event: "Democracy restored" },
      { year: "2010", event: "Major earthquake" },
    ],
    "China": [
      { year: "221 BC", event: "Qin Shi Huang unifies China" },
      { year: "206 BC", event: "Han dynasty begins" },
      { year: "1271", event: "Yuan (Mongol) dynasty" },
      { year: "1368", event: "Ming dynasty" },
      { year: "1644", event: "Qing dynasty" },
      { year: "1839", event: "First Opium War (British imperialism)" },
      { year: "1856", event: "Second Opium War" },
      { year: "1894", event: "First Sino-Japanese War" },
      { year: "1900", event: "Boxer Rebellion" },
      { year: "1912", event: "Republic of China" },
      { year: "1937", event: "Second Sino-Japanese War / WWII" },
      { year: "1949", event: "People's Republic established" },
      { year: "1958", event: "Great Leap Forward" },
      { year: "1966", event: "Cultural Revolution" },
      { year: "1978", event: "Deng Xiaoping reforms" },
      { year: "1989", event: "Tiananmen Square protests" },
    ],
    "Colombia": [
      { year: "1499", event: "Spanish colonization" },
      { year: "1819", event: "Independence (Battle of Boyacá)" },
      { year: "1899", event: "Thousand Days' War" },
      { year: "1903", event: "Panama separates" },
      { year: "1948", event: "La Violencia begins" },
      { year: "1964", event: "FARC guerrilla founded" },
      { year: "2016", event: "FARC peace deal" },
    ],
    "Congo": [
      { year: "1880", event: "French protectorate (Brazzaville)" },
      { year: "1960", event: "Independence" },
      { year: "1969", event: "Marxist state declared" },
      { year: "1992", event: "Multi-party democracy" },
      { year: "1997", event: "Civil war; Sassou Nguesso returns to power" },
    ],
    "Costa Rica": [
      { year: "1502", event: "Columbus arrives" },
      { year: "1821", event: "Independence from Spain" },
      { year: "1948", event: "Civil war; army abolished" },
      { year: "1949", event: "New constitution; women's suffrage" },
      { year: "1987", event: "Arias wins Nobel Peace Prize" },
    ],
    "Croatia": [
      { year: "925", event: "Kingdom of Croatia" },
      { year: "1102", event: "Personal union with Hungary" },
      { year: "1527", event: "Habsburg rule" },
      { year: "1918", event: "Joins Kingdom of Yugoslavia" },
      { year: "1941", event: "Puppet Ustasha state (WWII)" },
      { year: "1991", event: "Independence; Croatian War of Independence" },
      { year: "1995", event: "Operation Storm ends war" },
      { year: "2013", event: "Joins EU" },
    ],
    "Cuba": [
      { year: "1492", event: "Columbus arrives" },
      { year: "1511", event: "Spanish colonization" },
      { year: "1868", event: "Ten Years' War" },
      { year: "1895", event: "War of Independence" },
      { year: "1898", event: "Spanish-American War; US occupation" },
      { year: "1902", event: "Republic (under Platt Amendment)" },
      { year: "1959", event: "Cuban Revolution (Castro)" },
      { year: "1961", event: "Bay of Pigs invasion" },
      { year: "1962", event: "Cuban Missile Crisis" },
    ],
    "Czechia": [
      { year: "863", event: "Great Moravia (Cyril and Methodius)" },
      { year: "1212", event: "Kingdom of Bohemia" },
      { year: "1620", event: "Battle of White Mountain (Habsburg control)" },
      { year: "1918", event: "Czechoslovakia founded" },
      { year: "1938", event: "Munich Agreement; Nazi annexation" },
      { year: "1948", event: "Communist coup" },
      { year: "1968", event: "Prague Spring crushed by Soviet invasion" },
      { year: "1989", event: "Velvet Revolution" },
      { year: "1993", event: "Czech Republic (Velvet Divorce)" },
      { year: "2004", event: "Joins EU" },
    ],
    "Dem. Rep. Congo": [
      { year: "1390", event: "Kingdom of Kongo" },
      { year: "1885", event: "Congo Free State (Leopold II's brutal rule)" },
      { year: "1908", event: "Belgian Congo" },
      { year: "1960", event: "Independence; Lumumba assassinated" },
      { year: "1965", event: "Mobutu seizes power (Zaïre)" },
      { year: "1994", event: "Rwandan genocide spillover" },
      { year: "1997", event: "Mobutu overthrown by Kabila" },
      { year: "1998", event: "Second Congo War (Africa's World War)" },
      { year: "2003", event: "Peace agreement" },
    ],
    "Denmark": [
      { year: "800", event: "Viking Age" },
      { year: "965", event: "Christianization (Harald Bluetooth)" },
      { year: "1397", event: "Kalmar Union" },
      { year: "1536", event: "Reformation" },
      { year: "1849", event: "Constitutional monarchy" },
      { year: "1864", event: "Loses Schleswig-Holstein to Prussia" },
      { year: "1940", event: "German occupation (WWII)" },
      { year: "1945", event: "Liberation" },
      { year: "1973", event: "Joins EC (European Community)" },
    ],
    "Dominican Rep.": [
      { year: "1492", event: "Columbus arrives (Hispaniola)" },
      { year: "1844", event: "Independence from Haiti" },
      { year: "1916", event: "US military occupation" },
      { year: "1930", event: "Trujillo dictatorship begins" },
      { year: "1961", event: "Trujillo assassinated" },
      { year: "1965", event: "Civil war; US intervention" },
    ],
    "Ecuador": [
      { year: "1463", event: "Inca conquest" },
      { year: "1534", event: "Spanish conquest" },
      { year: "1822", event: "Independence (Battle of Pichincha)" },
      { year: "1941", event: "Border war with Peru" },
      { year: "2008", event: "New constitution" },
    ],
    "Egypt": [
      { year: "3100 BC", event: "Unification under first pharaoh" },
      { year: "332 BC", event: "Alexander the Great conquers" },
      { year: "30 BC", event: "Roman province" },
      { year: "642", event: "Arab conquest" },
      { year: "1517", event: "Ottoman conquest" },
      { year: "1798", event: "Napoleon's invasion" },
      { year: "1869", event: "Suez Canal opens" },
      { year: "1882", event: "British occupation" },
      { year: "1922", event: "Nominal independence" },
      { year: "1952", event: "Revolution & republic (Nasser)" },
      { year: "1956", event: "Suez Crisis" },
      { year: "1967", event: "Six-Day War" },
      { year: "1973", event: "Yom Kippur/October War" },
      { year: "2011", event: "Egyptian Revolution" },
    ],
    "El Salvador": [
      { year: "1525", event: "Spanish conquest" },
      { year: "1821", event: "Independence from Spain" },
      { year: "1932", event: "La Matanza massacre" },
      { year: "1979", event: "Civil war begins" },
      { year: "1992", event: "Peace accords" },
    ],
    "Eritrea": [
      { year: "1890", event: "Italian colony" },
      { year: "1941", event: "British administration" },
      { year: "1952", event: "Federated with Ethiopia" },
      { year: "1961", event: "War of independence begins" },
      { year: "1993", event: "Independence from Ethiopia" },
      { year: "1998", event: "Eritrean-Ethiopian War" },
    ],
    "Estonia": [
      { year: "1219", event: "Danish conquest" },
      { year: "1346", event: "Teutonic Order" },
      { year: "1629", event: "Swedish rule" },
      { year: "1710", event: "Russian Empire" },
      { year: "1918", event: "Independence declared" },
      { year: "1940", event: "Soviet occupation" },
      { year: "1941", event: "Nazi occupation" },
      { year: "1944", event: "Soviet re-occupation" },
      { year: "1991", event: "Independence restored" },
      { year: "2004", event: "Joins EU and NATO" },
    ],
    "Ethiopia": [
      { year: "980 BC", event: "Kingdom of Aksum" },
      { year: "1270", event: "Solomonic dynasty restored" },
      { year: "1896", event: "Defeats Italy at Battle of Adwa" },
      { year: "1935", event: "Italian invasion" },
      { year: "1941", event: "Liberation" },
      { year: "1974", event: "Derg military junta; emperor deposed" },
      { year: "1983", event: "Ethiopian famine" },
      { year: "1991", event: "EPRDF takes power" },
      { year: "1998", event: "Eritrean-Ethiopian War" },
      { year: "2020", event: "Tigray War begins" },
    ],
    "Finland": [
      { year: "1155", event: "Swedish rule begins (Northern Crusades)" },
      { year: "1809", event: "Russian Grand Duchy" },
      { year: "1917", event: "Independence from Russia" },
      { year: "1918", event: "Finnish Civil War" },
      { year: "1939", event: "Winter War (Soviet invasion)" },
      { year: "1941", event: "Continuation War" },
      { year: "1995", event: "Joins EU" },
      { year: "2023", event: "Joins NATO" },
    ],
    "France": [
      { year: "843", event: "Treaty of Verdun (West Francia)" },
      { year: "1337", event: "Hundred Years' War begins" },
      { year: "1789", event: "French Revolution" },
      { year: "1799", event: "Napoleon seizes power" },
      { year: "1804", event: "Napoleon crowned Emperor" },
      { year: "1815", event: "Waterloo; Bourbon restoration" },
      { year: "1830", event: "July Revolution" },
      { year: "1848", event: "Second Republic" },
      { year: "1870", event: "Franco-Prussian War; Third Republic" },
      { year: "1914", event: "World War I" },
      { year: "1940", event: "Fall of France; Vichy regime" },
      { year: "1944", event: "Liberation" },
      { year: "1954", event: "Defeat at Dien Bien Phu; Algerian War begins" },
      { year: "1958", event: "Fifth Republic (de Gaulle)" },
      { year: "1962", event: "Algerian independence; end of colonial empire" },
    ],
    "Georgia": [
      { year: "1008", event: "Unified Georgian kingdom (Bagrationi)" },
      { year: "1210", event: "Golden Age under Queen Tamar" },
      { year: "1801", event: "Russian annexation" },
      { year: "1918", event: "First Republic" },
      { year: "1921", event: "Soviet invasion" },
      { year: "1991", event: "Independence from USSR" },
      { year: "1992", event: "South Ossetia and Abkhazia wars" },
      { year: "2003", event: "Rose Revolution" },
      { year: "2008", event: "Russo-Georgian War" },
    ],
    "Germany": [
      { year: "800", event: "Charlemagne crowned Emperor" },
      { year: "962", event: "Holy Roman Empire" },
      { year: "1517", event: "Protestant Reformation (Luther)" },
      { year: "1618", event: "Thirty Years' War" },
      { year: "1871", event: "Unification under Bismarck" },
      { year: "1914", event: "World War I" },
      { year: "1918", event: "Weimar Republic" },
      { year: "1933", event: "Hitler takes power; Nazi regime" },
      { year: "1939", event: "World War II begins" },
      { year: "1945", event: "WWII ends; Germany divided" },
      { year: "1961", event: "Berlin Wall built" },
      { year: "1989", event: "Berlin Wall falls" },
      { year: "1990", event: "Reunification" },
    ],
    "Ghana": [
      { year: "1200", event: "Akan states emerge" },
      { year: "1482", event: "Portuguese build Elmina Castle (slave trade)" },
      { year: "1874", event: "British Gold Coast colony" },
      { year: "1900", event: "War of the Golden Stool" },
      { year: "1957", event: "First sub-Saharan African independence (Nkrumah)" },
      { year: "1966", event: "Nkrumah overthrown" },
      { year: "1992", event: "Fourth Republic" },
    ],
    "Greece": [
      { year: "508 BC", event: "Athenian democracy established" },
      { year: "336 BC", event: "Alexander the Great's empire" },
      { year: "146 BC", event: "Roman conquest" },
      { year: "1453", event: "Fall of Constantinople to Ottomans" },
      { year: "1821", event: "Greek War of Independence" },
      { year: "1912", event: "Balkan Wars" },
      { year: "1940", event: "Greco-Italian War; German occupation" },
      { year: "1946", event: "Greek Civil War" },
      { year: "1967", event: "Military junta" },
      { year: "1974", event: "Democracy restored" },
      { year: "1981", event: "Joins EC" },
    ],
    "Greenland": [
      { year: "2500 BC", event: "Paleo-Inuit peoples arrive" },
      { year: "986", event: "Norse settlement (Erik the Red)" },
      { year: "1261", event: "Comes under Norwegian Crown" },
      { year: "1350", event: "Norse colonies disappear" },
      { year: "1380", event: "Danish-Norwegian rule" },
      { year: "1721", event: "Danish re-colonization (Hans Egede)" },
      { year: "1814", event: "Becomes solely Danish (Treaty of Kiel)" },
      { year: "1940", event: "US protection during WWII" },
      { year: "1953", event: "Becomes integral part of Denmark (colony status ends)" },
      { year: "1979", event: "Home Rule granted" },
      { year: "2009", event: "Self-Rule Act (expanded autonomy)" },
    ],
    "Guatemala": [
      { year: "2000 BC", event: "Maya civilization flourishes" },
      { year: "1524", event: "Spanish conquest" },
      { year: "1821", event: "Independence" },
      { year: "1954", event: "CIA-backed coup" },
      { year: "1960", event: "Civil war begins" },
      { year: "1996", event: "Peace accords (end of 36-year civil war)" },
    ],
    "Guinea": [
      { year: "1725", event: "Imamate of Futa Jallon" },
      { year: "1898", event: "French colony" },
      { year: "1958", event: "Independence (first French African colony)" },
      { year: "1984", event: "Sékou Touré dies; military takeover" },
      { year: "2010", event: "First democratic election" },
    ],
    "Haiti": [
      { year: "1492", event: "Columbus arrives (Hispaniola)" },
      { year: "1697", event: "French colony (Saint-Domingue)" },
      { year: "1791", event: "Haitian Revolution begins (slave revolt)" },
      { year: "1804", event: "Independence (first Black republic)" },
      { year: "1915", event: "US military occupation" },
      { year: "1957", event: "Duvalier dictatorship begins" },
      { year: "2010", event: "Devastating earthquake" },
    ],
    "Honduras": [
      { year: "1502", event: "Columbus arrives" },
      { year: "1821", event: "Independence from Spain" },
      { year: "1899", event: "US banana companies dominate" },
      { year: "1969", event: "Football War with El Salvador" },
      { year: "2009", event: "Military coup" },
    ],
    "Hungary": [
      { year: "896", event: "Magyar conquest of Carpathian Basin" },
      { year: "1000", event: "Kingdom of Hungary (St. Stephen)" },
      { year: "1241", event: "Mongol invasion" },
      { year: "1526", event: "Battle of Mohács; Ottoman conquest" },
      { year: "1686", event: "Habsburg reconquest of Buda" },
      { year: "1848", event: "Revolution against Habsburgs" },
      { year: "1867", event: "Austria-Hungary formed" },
      { year: "1918", event: "Independence" },
      { year: "1920", event: "Treaty of Trianon (loses 2/3 of territory)" },
      { year: "1945", event: "Soviet occupation" },
      { year: "1956", event: "Hungarian Revolution crushed by Soviets" },
      { year: "1989", event: "End of communism" },
      { year: "2004", event: "Joins EU" },
    ],
    "Iceland": [
      { year: "874", event: "Norse settlement" },
      { year: "930", event: "Althing founded (oldest parliament)" },
      { year: "1262", event: "Norwegian rule" },
      { year: "1380", event: "Danish rule" },
      { year: "1944", event: "Republic established" },
      { year: "1958", event: "First Cod War with UK" },
      { year: "2008", event: "Financial crisis and banking collapse" },
    ],
    "India": [
      { year: "2500 BC", event: "Indus Valley civilization" },
      { year: "322 BC", event: "Maurya Empire (Chandragupta)" },
      { year: "320", event: "Gupta Empire (Golden Age)" },
      { year: "1206", event: "Delhi Sultanate" },
      { year: "1526", event: "Mughal Empire (Babur)" },
      { year: "1757", event: "Battle of Plassey (British East India Company)" },
      { year: "1857", event: "Indian Rebellion (Sepoy Mutiny)" },
      { year: "1858", event: "British Crown rule (British Raj)" },
      { year: "1919", event: "Jallianwala Bagh massacre" },
      { year: "1930", event: "Salt March (Gandhi)" },
      { year: "1943", event: "Bengal famine" },
      { year: "1947", event: "Independence & partition" },
      { year: "1950", event: "Republic established" },
      { year: "1962", event: "Sino-Indian War" },
      { year: "1965", event: "Indo-Pakistani War" },
      { year: "1971", event: "Indo-Pakistani War (Bangladesh liberation)" },
      { year: "1991", event: "Economic liberalization" },
    ],
    "Indonesia": [
      { year: "700", event: "Srivijaya Empire" },
      { year: "1293", event: "Majapahit Empire" },
      { year: "1602", event: "Dutch East India Company (VOC)" },
      { year: "1830", event: "Dutch Cultivation System (forced labor)" },
      { year: "1942", event: "Japanese occupation" },
      { year: "1945", event: "Independence declared" },
      { year: "1949", event: "Dutch recognize sovereignty" },
      { year: "1965", event: "Anti-communist massacres; Suharto rises" },
      { year: "1975", event: "Invasion of East Timor" },
      { year: "1998", event: "Reformasi; Suharto falls" },
      { year: "2004", event: "Indian Ocean tsunami" },
    ],
    "Iran": [
      { year: "550 BC", event: "Achaemenid (Persian) Empire" },
      { year: "330 BC", event: "Alexander the Great conquers" },
      { year: "224", event: "Sasanian Empire" },
      { year: "651", event: "Arab conquest; Islamization" },
      { year: "1501", event: "Safavid dynasty (Shia state)" },
      { year: "1906", event: "Constitutional Revolution" },
      { year: "1925", event: "Pahlavi dynasty" },
      { year: "1941", event: "Anglo-Soviet invasion" },
      { year: "1953", event: "CIA-backed coup against Mosaddegh" },
      { year: "1979", event: "Islamic Revolution" },
      { year: "1980", event: "Iran-Iraq War begins" },
      { year: "1988", event: "Iran-Iraq War ends" },
    ],
    "Iraq": [
      { year: "3500 BC", event: "Mesopotamian civilization (Sumer)" },
      { year: "2334 BC", event: "Akkadian Empire" },
      { year: "539 BC", event: "Persian conquest" },
      { year: "762", event: "Baghdad founded (Abbasid capital)" },
      { year: "1258", event: "Mongol destruction of Baghdad" },
      { year: "1534", event: "Ottoman conquest" },
      { year: "1920", event: "British mandate" },
      { year: "1932", event: "Independence" },
      { year: "1958", event: "Monarchy overthrown" },
      { year: "1979", event: "Saddam Hussein takes power" },
      { year: "1980", event: "Iran-Iraq War" },
      { year: "1990", event: "Invasion of Kuwait" },
      { year: "1991", event: "Gulf War" },
      { year: "2003", event: "US-led invasion; Saddam toppled" },
      { year: "2014", event: "ISIS seizes territory" },
      { year: "2017", event: "ISIS defeated in Mosul" },
    ],
    "Ireland": [
      { year: "432", event: "St. Patrick arrives" },
      { year: "795", event: "Viking raids begin" },
      { year: "1171", event: "Anglo-Norman invasion" },
      { year: "1541", event: "Kingdom of Ireland under English Crown" },
      { year: "1649", event: "Cromwellian conquest" },
      { year: "1798", event: "Irish Rebellion" },
      { year: "1845", event: "Great Famine begins" },
      { year: "1916", event: "Easter Rising" },
      { year: "1919", event: "Irish War of Independence" },
      { year: "1922", event: "Irish Free State" },
      { year: "1949", event: "Republic of Ireland" },
      { year: "1969", event: "The Troubles begin" },
      { year: "1998", event: "Good Friday Agreement" },
    ],
    "Israel": [
      { year: "1000 BC", event: "Kingdom of Israel (David)" },
      { year: "586 BC", event: "Babylonian exile" },
      { year: "70", event: "Roman destruction of Jerusalem" },
      { year: "1917", event: "Balfour Declaration" },
      { year: "1948", event: "State of Israel declared; Arab-Israeli War" },
      { year: "1967", event: "Six-Day War" },
      { year: "1973", event: "Yom Kippur War" },
      { year: "1979", event: "Peace with Egypt (Camp David)" },
      { year: "1987", event: "First Intifada" },
      { year: "1993", event: "Oslo Accords" },
      { year: "2000", event: "Second Intifada" },
      { year: "2023", event: "October 7 attack and Gaza war" },
    ],
    "Italy": [
      { year: "753 BC", event: "Rome founded (traditional date)" },
      { year: "27 BC", event: "Roman Empire begins" },
      { year: "476", event: "Fall of Western Roman Empire" },
      { year: "1300", event: "Renaissance begins" },
      { year: "1494", event: "Italian Wars (foreign domination)" },
      { year: "1861", event: "Unification (Risorgimento)" },
      { year: "1915", event: "Enters World War I" },
      { year: "1922", event: "Mussolini's Fascist regime" },
      { year: "1940", event: "Enters World War II" },
      { year: "1943", event: "Armistice; German occupation" },
      { year: "1946", event: "Republic (monarchy abolished)" },
    ],
    "Ivory Coast": [
      { year: "1400", event: "Kong Empire" },
      { year: "1843", event: "French protectorate" },
      { year: "1893", event: "French colony" },
      { year: "1960", event: "Independence (Houphouët-Boigny)" },
      { year: "2002", event: "Civil war" },
      { year: "2010", event: "Post-election crisis" },
    ],
    "Jamaica": [
      { year: "1509", event: "Spanish colonization" },
      { year: "1655", event: "British conquest" },
      { year: "1831", event: "Baptist War (slave rebellion)" },
      { year: "1838", event: "Emancipation" },
      { year: "1962", event: "Independence" },
    ],
    "Japan": [
      { year: "710", event: "Nara period (first permanent capital)" },
      { year: "794", event: "Heian period" },
      { year: "1185", event: "Kamakura shogunate (samurai era)" },
      { year: "1274", event: "First Mongol invasion attempt" },
      { year: "1467", event: "Ōnin War; Warring States period" },
      { year: "1603", event: "Tokugawa shogunate (isolationist era)" },
      { year: "1853", event: "Perry's Black Ships force opening" },
      { year: "1868", event: "Meiji Restoration (modernization)" },
      { year: "1894", event: "First Sino-Japanese War" },
      { year: "1905", event: "Defeats Russia in Russo-Japanese War" },
      { year: "1910", event: "Annexation of Korea" },
      { year: "1931", event: "Invasion of Manchuria" },
      { year: "1937", event: "Second Sino-Japanese War" },
      { year: "1941", event: "Pearl Harbor; enters WWII" },
      { year: "1945", event: "Atomic bombings; surrender; US occupation" },
      { year: "1947", event: "Post-war constitution (pacifist)" },
      { year: "1968", event: "Becomes world's second-largest economy" },
    ],
    "Jordan": [
      { year: "312 BC", event: "Nabataean Kingdom (Petra)" },
      { year: "106", event: "Roman province" },
      { year: "1516", event: "Ottoman rule" },
      { year: "1921", event: "Emirate of Transjordan (British mandate)" },
      { year: "1946", event: "Independence" },
      { year: "1948", event: "First Arab-Israeli War" },
      { year: "1967", event: "Six-Day War (loses West Bank)" },
      { year: "1970", event: "Black September" },
      { year: "1994", event: "Peace treaty with Israel" },
    ],
    "Kazakhstan": [
      { year: "1465", event: "Kazakh Khanate" },
      { year: "1731", event: "Russian influence begins" },
      { year: "1847", event: "Full Russian control" },
      { year: "1936", event: "Kazakh SSR" },
      { year: "1949", event: "Soviet nuclear testing begins at Semipalatinsk" },
      { year: "1991", event: "Last Soviet republic to declare independence" },
      { year: "1997", event: "Capital moved to Astana" },
      { year: "2022", event: "Bloody January protests" },
    ],
    "Kenya": [
      { year: "700", event: "Swahili city-states" },
      { year: "1895", event: "British protectorate" },
      { year: "1920", event: "Kenya Colony" },
      { year: "1952", event: "Mau Mau uprising" },
      { year: "1963", event: "Independence (Kenyatta)" },
      { year: "2007", event: "Post-election violence" },
      { year: "2010", event: "New constitution" },
    ],
    "Kosovo": [
      { year: "1389", event: "Battle of Kosovo (Ottoman expansion)" },
      { year: "1912", event: "Annexed by Serbia" },
      { year: "1998", event: "Kosovo War" },
      { year: "1999", event: "NATO intervention; UN administration" },
      { year: "2008", event: "Declaration of independence" },
    ],
    "Kuwait": [
      { year: "1752", event: "Al-Sabah dynasty" },
      { year: "1899", event: "British protectorate" },
      { year: "1938", event: "Oil discovered" },
      { year: "1961", event: "Independence" },
      { year: "1990", event: "Iraqi invasion" },
      { year: "1991", event: "Liberation (Gulf War)" },
    ],
    "Laos": [
      { year: "1353", event: "Lan Xang kingdom" },
      { year: "1893", event: "French protectorate" },
      { year: "1953", event: "Independence" },
      { year: "1964", event: "Secret US bombing campaign" },
      { year: "1975", event: "Communist Pathet Lao takes power" },
    ],
    "Latvia": [
      { year: "1201", event: "Riga founded (Teutonic Order)" },
      { year: "1561", event: "Polish-Lithuanian rule" },
      { year: "1710", event: "Russian Empire" },
      { year: "1918", event: "Independence declared" },
      { year: "1940", event: "Soviet occupation" },
      { year: "1941", event: "Nazi occupation; Holocaust" },
      { year: "1944", event: "Soviet re-occupation" },
      { year: "1991", event: "Independence restored" },
      { year: "2004", event: "Joins EU and NATO" },
    ],
    "Lebanon": [
      { year: "3000 BC", event: "Phoenician civilization" },
      { year: "64 BC", event: "Roman province" },
      { year: "636", event: "Arab conquest" },
      { year: "1516", event: "Ottoman rule" },
      { year: "1920", event: "French mandate" },
      { year: "1943", event: "Independence" },
      { year: "1975", event: "Civil war begins" },
      { year: "1982", event: "Israeli invasion" },
      { year: "1990", event: "Civil war ends" },
      { year: "2005", event: "Cedar Revolution" },
      { year: "2020", event: "Beirut port explosion" },
    ],
    "Libya": [
      { year: "631 BC", event: "Greek colony of Cyrene" },
      { year: "642", event: "Arab conquest" },
      { year: "1551", event: "Ottoman rule" },
      { year: "1911", event: "Italian colonization (Italo-Turkish War)" },
      { year: "1943", event: "Allied liberation (WWII)" },
      { year: "1951", event: "Independence" },
      { year: "1969", event: "Gaddafi seizes power" },
      { year: "2011", event: "Civil war; Gaddafi overthrown and killed" },
    ],
    "Lithuania": [
      { year: "1253", event: "Kingdom of Lithuania" },
      { year: "1386", event: "Union with Poland (Christianization)" },
      { year: "1569", event: "Polish-Lithuanian Commonwealth" },
      { year: "1795", event: "Russian annexation (Partitions)" },
      { year: "1918", event: "Independence" },
      { year: "1940", event: "Soviet occupation" },
      { year: "1941", event: "Nazi occupation; Holocaust" },
      { year: "1990", event: "First Soviet republic to declare independence" },
      { year: "2004", event: "Joins EU and NATO" },
    ],
    "Madagascar": [
      { year: "500", event: "Austronesian settlement" },
      { year: "1500", event: "Portuguese arrival" },
      { year: "1817", event: "Merina Kingdom recognized by Britain" },
      { year: "1896", event: "French colony" },
      { year: "1947", event: "Malagasy Uprising (French repression)" },
      { year: "1960", event: "Independence" },
    ],
    "Malaysia": [
      { year: "1400", event: "Malacca Sultanate" },
      { year: "1511", event: "Portuguese conquest of Malacca" },
      { year: "1641", event: "Dutch control" },
      { year: "1824", event: "British control (Anglo-Dutch Treaty)" },
      { year: "1942", event: "Japanese occupation" },
      { year: "1948", event: "Malayan Emergency (communist insurgency)" },
      { year: "1957", event: "Independence (Malaya)" },
      { year: "1963", event: "Malaysia formed (with Sabah, Sarawak, Singapore)" },
      { year: "1965", event: "Singapore expelled" },
      { year: "1969", event: "Racial riots" },
    ],
    "Mali": [
      { year: "300", event: "Ghana Empire" },
      { year: "1235", event: "Mali Empire (Sundiata Keita)" },
      { year: "1324", event: "Mansa Musa's pilgrimage to Mecca" },
      { year: "1468", event: "Songhai Empire" },
      { year: "1591", event: "Moroccan conquest" },
      { year: "1892", event: "French colony" },
      { year: "1960", event: "Independence" },
      { year: "2012", event: "Tuareg rebellion; Islamist insurgency" },
      { year: "2021", event: "Military coup" },
    ],
    "Mexico": [
      { year: "1500 BC", event: "Olmec civilization" },
      { year: "250", event: "Maya Classic period" },
      { year: "1325", event: "Tenochtitlan founded (Aztec)" },
      { year: "1521", event: "Spanish conquest (Cortés)" },
      { year: "1810", event: "War of Independence begins" },
      { year: "1821", event: "Independence" },
      { year: "1846", event: "Mexican-American War" },
      { year: "1862", event: "French intervention; Battle of Puebla" },
      { year: "1910", event: "Mexican Revolution" },
      { year: "1917", event: "Revolutionary constitution" },
      { year: "2000", event: "PRI loses power after 71 years" },
    ],
    "Mongolia": [
      { year: "209 BC", event: "Xiongnu Empire" },
      { year: "1206", event: "Genghis Khan unifies Mongols" },
      { year: "1279", event: "Largest contiguous land empire" },
      { year: "1368", event: "Yuan dynasty falls in China" },
      { year: "1691", event: "Qing dynasty rule" },
      { year: "1911", event: "Independence from Qing China" },
      { year: "1924", event: "Mongolian People's Republic (Soviet satellite)" },
      { year: "1990", event: "Democratic revolution" },
    ],
    "Morocco": [
      { year: "788", event: "Idrisid dynasty (first Moroccan state)" },
      { year: "1062", event: "Almoravid Empire" },
      { year: "1147", event: "Almohad dynasty" },
      { year: "1912", event: "French and Spanish protectorates" },
      { year: "1921", event: "Rif War" },
      { year: "1956", event: "Independence" },
      { year: "1975", event: "Green March into Western Sahara" },
      { year: "1999", event: "Mohammed VI ascends throne" },
    ],
    "Mozambique": [
      { year: "1498", event: "Vasco da Gama arrives" },
      { year: "1505", event: "Portuguese colony established" },
      { year: "1964", event: "War of independence begins" },
      { year: "1975", event: "Independence from Portugal" },
      { year: "1977", event: "Civil war begins" },
      { year: "1992", event: "Peace agreement" },
    ],
    "Myanmar": [
      { year: "1044", event: "Pagan Kingdom (first unified state)" },
      { year: "1287", event: "Mongol invasion; Pagan falls" },
      { year: "1824", event: "First Anglo-Burmese War" },
      { year: "1852", event: "Second Anglo-Burmese War" },
      { year: "1885", event: "Third Anglo-Burmese War; full British control" },
      { year: "1942", event: "Japanese occupation (WWII)" },
      { year: "1948", event: "Independence" },
      { year: "1962", event: "Military coup (Ne Win)" },
      { year: "1988", event: "Pro-democracy uprising; military crackdown" },
      { year: "2010", event: "Aung San Suu Kyi released" },
      { year: "2021", event: "Military coup" },
    ],
    "Namibia": [
      { year: "1884", event: "German colony (South West Africa)" },
      { year: "1904", event: "Herero and Nama genocide" },
      { year: "1915", event: "South African occupation (WWI)" },
      { year: "1966", event: "Independence war begins (SWAPO)" },
      { year: "1990", event: "Independence" },
    ],
    "Nepal": [
      { year: "1769", event: "Unification under Prithvi Narayan Shah" },
      { year: "1816", event: "Sugauli Treaty with British India" },
      { year: "1846", event: "Rana dynasty (autocratic rule)" },
      { year: "1951", event: "Democracy movement; Rana overthrown" },
      { year: "1996", event: "Maoist insurgency begins" },
      { year: "2006", event: "Peace agreement; end of civil war" },
      { year: "2008", event: "Republic declared (monarchy abolished)" },
      { year: "2015", event: "Devastating earthquake" },
    ],
    "Netherlands": [
      { year: "1568", event: "Dutch Revolt against Spain" },
      { year: "1581", event: "Declaration of independence" },
      { year: "1602", event: "VOC (Dutch East India Company) founded" },
      { year: "1621", event: "WIC; Dutch colonial empire expands" },
      { year: "1648", event: "Independence recognized (Westphalia)" },
      { year: "1652", event: "Cape Colony founded; Anglo-Dutch Wars" },
      { year: "1795", event: "French occupation" },
      { year: "1815", event: "Kingdom of Netherlands established" },
      { year: "1940", event: "Nazi invasion and occupation" },
      { year: "1945", event: "Liberation" },
      { year: "1949", event: "Indonesian independence recognized" },
      { year: "1975", event: "Suriname independence" },
    ],
    "New Zealand": [
      { year: "1300", event: "Polynesian (Māori) settlement" },
      { year: "1840", event: "Treaty of Waitangi (British sovereignty)" },
      { year: "1845", event: "New Zealand Wars begin" },
      { year: "1893", event: "First country with women's suffrage" },
      { year: "1907", event: "Dominion status" },
      { year: "1915", event: "Gallipoli campaign (ANZAC)" },
      { year: "1985", event: "Anti-nuclear policy" },
    ],
    "Nicaragua": [
      { year: "1524", event: "Spanish colonization" },
      { year: "1821", event: "Independence from Spain" },
      { year: "1912", event: "US military occupation" },
      { year: "1936", event: "Somoza dynasty begins" },
      { year: "1979", event: "Sandinista Revolution" },
      { year: "1981", event: "Contra War" },
      { year: "1990", event: "Democratic transition" },
    ],
    "Niger": [
      { year: "1000", event: "Hausa city-states" },
      { year: "1460", event: "Songhai Empire expansion" },
      { year: "1900", event: "French conquest" },
      { year: "1960", event: "Independence" },
      { year: "2023", event: "Military coup" },
    ],
    "Nigeria": [
      { year: "500 BC", event: "Nok civilization" },
      { year: "1000", event: "Hausa city-states and Kanem-Bornu" },
      { year: "1472", event: "Portuguese contact" },
      { year: "1804", event: "Sokoto Caliphate (Fulani jihad)" },
      { year: "1861", event: "British colonization of Lagos" },
      { year: "1914", event: "British unify Northern and Southern Nigeria" },
      { year: "1960", event: "Independence" },
      { year: "1967", event: "Biafra War (civil war)" },
      { year: "1970", event: "Civil war ends" },
      { year: "1999", event: "Fourth Republic (democracy restored)" },
    ],
    "North Korea": [
      { year: "668", event: "Unified Silla Kingdom" },
      { year: "918", event: "Goryeo dynasty" },
      { year: "1392", event: "Joseon dynasty" },
      { year: "1910", event: "Japanese annexation" },
      { year: "1945", event: "Division at 38th parallel" },
      { year: "1948", event: "DPRK established (Kim Il-sung)" },
      { year: "1950", event: "Korean War begins" },
      { year: "1953", event: "Armistice" },
      { year: "1994", event: "Kim Jong-il succeeds" },
      { year: "2006", event: "First nuclear test" },
    ],
    "North Macedonia": [
      { year: "1014", event: "Byzantine conquest (Battle of Kleidion)" },
      { year: "1392", event: "Ottoman conquest" },
      { year: "1913", event: "Annexed by Serbia (Balkan Wars)" },
      { year: "1944", event: "Part of Yugoslavia" },
      { year: "1991", event: "Independence" },
      { year: "2019", event: "Name change from Macedonia" },
    ],
    "Norway": [
      { year: "793", event: "Viking Age begins (Lindisfarne raid)" },
      { year: "872", event: "Harald Fairhair unifies Norway" },
      { year: "1397", event: "Kalmar Union (with Denmark & Sweden)" },
      { year: "1814", event: "Constitution (Eidsvoll)" },
      { year: "1905", event: "Independence from Sweden" },
      { year: "1940", event: "German invasion (WWII)" },
      { year: "1945", event: "Liberation" },
      { year: "1969", event: "Oil discovered in North Sea" },
    ],
    "Pakistan": [
      { year: "2500 BC", event: "Indus Valley civilization" },
      { year: "712", event: "Arab conquest of Sindh" },
      { year: "1526", event: "Mughal Empire" },
      { year: "1857", event: "British Crown rule" },
      { year: "1940", event: "Lahore Resolution (demand for Pakistan)" },
      { year: "1947", event: "Independence & partition (mass migration)" },
      { year: "1948", event: "First Kashmir War" },
      { year: "1965", event: "Second Indo-Pakistani War" },
      { year: "1971", event: "Bangladesh separates; third war with India" },
      { year: "1998", event: "Nuclear weapons tests" },
    ],
    "Palestine": [
      { year: "1516", event: "Ottoman rule" },
      { year: "1920", event: "British mandate" },
      { year: "1948", event: "Nakba (displacement during Israeli independence)" },
      { year: "1964", event: "PLO founded" },
      { year: "1987", event: "First Intifada" },
      { year: "1993", event: "Oslo Accords; Palestinian Authority" },
      { year: "2007", event: "Hamas takes control of Gaza" },
      { year: "2023", event: "October 7 attack; Israel-Gaza war" },
    ],
    "Panama": [
      { year: "1501", event: "Spanish colonization" },
      { year: "1821", event: "Independence from Spain (joins Colombia)" },
      { year: "1903", event: "Separates from Colombia (US-backed)" },
      { year: "1914", event: "Panama Canal opens" },
      { year: "1989", event: "US invasion; Noriega ousted" },
      { year: "1999", event: "Canal returned to Panama" },
    ],
    "Papua New Guinea": [
      { year: "1545", event: "Portuguese sighting" },
      { year: "1884", event: "German and British colonies" },
      { year: "1914", event: "Australian control (WWI)" },
      { year: "1942", event: "Japanese invasion (WWII)" },
      { year: "1975", event: "Independence" },
    ],
    "Paraguay": [
      { year: "1537", event: "Spanish colonization" },
      { year: "1811", event: "Independence" },
      { year: "1864", event: "War of the Triple Alliance (catastrophic losses)" },
      { year: "1932", event: "Chaco War with Bolivia" },
      { year: "1954", event: "Stroessner dictatorship begins" },
      { year: "1989", event: "Democracy restored" },
    ],
    "Peru": [
      { year: "3000 BC", event: "Caral civilization" },
      { year: "1438", event: "Inca Empire rises" },
      { year: "1533", event: "Spanish conquest (Pizarro)" },
      { year: "1542", event: "Viceroyalty of Peru" },
      { year: "1780", event: "Túpac Amaru II rebellion" },
      { year: "1821", event: "Independence" },
      { year: "1879", event: "War of the Pacific" },
      { year: "1980", event: "Democracy restored; Shining Path insurgency" },
      { year: "2000", event: "End of Fujimori era" },
    ],
    "Philippines": [
      { year: "1521", event: "Magellan arrives" },
      { year: "1565", event: "Spanish colonization" },
      { year: "1896", event: "Revolution against Spain" },
      { year: "1898", event: "Independence declared; US colonization begins" },
      { year: "1899", event: "Philippine-American War" },
      { year: "1942", event: "Japanese occupation (WWII)" },
      { year: "1946", event: "Full independence" },
      { year: "1972", event: "Marcos declares martial law" },
      { year: "1986", event: "People Power Revolution" },
    ],
    "Poland": [
      { year: "966", event: "Baptism of Poland (Christianization)" },
      { year: "1385", event: "Union with Lithuania" },
      { year: "1569", event: "Polish-Lithuanian Commonwealth" },
      { year: "1683", event: "Battle of Vienna" },
      { year: "1772", event: "First Partition" },
      { year: "1795", event: "Third Partition (Poland erased)" },
      { year: "1918", event: "Independence restored" },
      { year: "1939", event: "German and Soviet invasion; WWII begins" },
      { year: "1945", event: "Communist state under Soviet influence" },
      { year: "1980", event: "Solidarity movement" },
      { year: "1989", event: "End of communist rule" },
      { year: "2004", event: "Joins EU" },
    ],
    "Portugal": [
      { year: "1139", event: "Kingdom established (Afonso Henriques)" },
      { year: "1415", event: "Capture of Ceuta; Age of Discovery begins" },
      { year: "1498", event: "Vasco da Gama reaches India" },
      { year: "1500", event: "Brazil claimed" },
      { year: "1580", event: "Spanish Habsburg rule" },
      { year: "1640", event: "Restoration of independence" },
      { year: "1755", event: "Great Lisbon earthquake" },
      { year: "1808", event: "Napoleonic invasion; court flees to Brazil" },
      { year: "1910", event: "Republic proclaimed" },
      { year: "1926", event: "Military dictatorship; Estado Novo" },
      { year: "1961", event: "Colonial wars in Africa begin" },
      { year: "1974", event: "Carnation Revolution; end of dictatorship" },
      { year: "1975", event: "African colonies gain independence" },
      { year: "1986", event: "Joins EC" },
    ],
    "Romania": [
      { year: "106", event: "Roman province of Dacia" },
      { year: "1330", event: "Wallachia established" },
      { year: "1476", event: "Vlad the Impaler's era" },
      { year: "1859", event: "Unification of Wallachia and Moldavia" },
      { year: "1877", event: "Independence from Ottomans" },
      { year: "1918", event: "Greater Romania (gains Transylvania)" },
      { year: "1940", event: "Territorial losses; Axis alliance" },
      { year: "1947", event: "Communist state" },
      { year: "1965", event: "Ceaușescu era" },
      { year: "1989", event: "Revolution; Ceaușescu executed" },
      { year: "2007", event: "Joins EU" },
    ],
    "Russia": [
      { year: "882", event: "Kievan Rus (Oleg of Novgorod)" },
      { year: "1237", event: "Mongol invasion (Golden Horde)" },
      { year: "1480", event: "End of Mongol rule" },
      { year: "1547", event: "Tsardom of Russia (Ivan the Terrible)" },
      { year: "1703", event: "St. Petersburg founded (Peter the Great)" },
      { year: "1812", event: "Napoleon's invasion and retreat" },
      { year: "1861", event: "Serfdom abolished" },
      { year: "1905", event: "Revolution; Bloody Sunday" },
      { year: "1914", event: "Enters World War I" },
      { year: "1917", event: "February and October Revolutions" },
      { year: "1918", event: "Russian Civil War" },
      { year: "1922", event: "USSR established" },
      { year: "1941", event: "Nazi invasion (Great Patriotic War)" },
      { year: "1945", event: "Victory in WWII" },
      { year: "1962", event: "Cuban Missile Crisis" },
      { year: "1979", event: "Soviet-Afghan War" },
      { year: "1986", event: "Chernobyl disaster" },
      { year: "1991", event: "Soviet Union dissolves" },
      { year: "1994", event: "First Chechen War" },
      { year: "2014", event: "Annexation of Crimea" },
      { year: "2022", event: "Full-scale invasion of Ukraine" },
    ],
    "Rwanda": [
      { year: "1600", event: "Kingdom of Rwanda" },
      { year: "1899", event: "German East Africa" },
      { year: "1916", event: "Belgian control" },
      { year: "1962", event: "Independence" },
      { year: "1990", event: "RPF invasion; civil war begins" },
      { year: "1994", event: "Genocide against Tutsi (~800,000 killed)" },
      { year: "1994", event: "RPF victory; Kagame era" },
    ],
    "Saudi Arabia": [
      { year: "622", event: "Islam founded in Medina" },
      { year: "1744", event: "First Saudi state" },
      { year: "1818", event: "Ottoman-Egyptian destruction of first state" },
      { year: "1902", event: "Ibn Saud recaptures Riyadh" },
      { year: "1932", event: "Kingdom unified" },
      { year: "1938", event: "Oil discovered" },
      { year: "1973", event: "Oil embargo" },
      { year: "1990", event: "Gulf War coalition base" },
      { year: "2016", event: "Vision 2030 announced" },
    ],
    "Senegal": [
      { year: "1200", event: "Jolof Empire" },
      { year: "1444", event: "Portuguese arrive (slave trade)" },
      { year: "1677", event: "French trading posts (Gorée Island)" },
      { year: "1895", event: "French West Africa" },
      { year: "1960", event: "Independence" },
      { year: "2000", event: "First democratic transfer of power" },
      { year: "2024", event: "Bassirou Diomaye Faye elected" },
    ],
    "Serbia": [
      { year: "1217", event: "Serbian Kingdom" },
      { year: "1346", event: "Serbian Empire (Stefan Dušan)" },
      { year: "1389", event: "Battle of Kosovo" },
      { year: "1459", event: "Ottoman conquest" },
      { year: "1804", event: "Serbian Revolution" },
      { year: "1878", event: "Independence recognized" },
      { year: "1912", event: "Balkan Wars" },
      { year: "1914", event: "WWI begins (assassination crisis)" },
      { year: "1918", event: "Part of Yugoslavia" },
      { year: "1991", event: "Yugoslav Wars begin" },
      { year: "1999", event: "NATO bombing over Kosovo" },
      { year: "2006", event: "Independence (Montenegro separates)" },
    ],
    "Singapore": [
      { year: "1299", event: "Kingdom of Singapura" },
      { year: "1819", event: "Raffles establishes British trading post" },
      { year: "1942", event: "Fall of Singapore to Japan" },
      { year: "1959", event: "Self-governance; Lee Kuan Yew" },
      { year: "1963", event: "Joins Malaysia" },
      { year: "1965", event: "Expelled from Malaysia; independence" },
      { year: "1990", event: "Becomes global financial hub" },
    ],
    "Slovakia": [
      { year: "833", event: "Great Moravia" },
      { year: "1000", event: "Part of Kingdom of Hungary" },
      { year: "1918", event: "Czechoslovakia founded" },
      { year: "1939", event: "Nazi client state" },
      { year: "1945", event: "Czechoslovakia restored" },
      { year: "1993", event: "Independence (Velvet Divorce)" },
      { year: "2004", event: "Joins EU and NATO" },
    ],
    "Slovenia": [
      { year: "1278", event: "Habsburg rule" },
      { year: "1918", event: "Part of Yugoslavia" },
      { year: "1991", event: "Independence (Ten-Day War)" },
      { year: "2004", event: "Joins EU and NATO" },
    ],
    "Somalia": [
      { year: "100", event: "Ancient trade with Romans" },
      { year: "1200", event: "Ajuran Sultanate" },
      { year: "1884", event: "Colonial partition (British, Italian, French)" },
      { year: "1960", event: "Independence & unification" },
      { year: "1969", event: "Siad Barre military coup" },
      { year: "1977", event: "Ogaden War with Ethiopia" },
      { year: "1991", event: "Civil war; state collapse" },
      { year: "2012", event: "Federal government re-established" },
    ],
    "South Africa": [
      { year: "1652", event: "Dutch East India Company settlement" },
      { year: "1806", event: "British take control of Cape" },
      { year: "1835", event: "Great Trek (Boer expansion)" },
      { year: "1879", event: "Anglo-Zulu War" },
      { year: "1899", event: "Second Boer War" },
      { year: "1910", event: "Union of South Africa" },
      { year: "1913", event: "Natives Land Act" },
      { year: "1948", event: "Apartheid formally begins" },
      { year: "1960", event: "Sharpeville massacre" },
      { year: "1964", event: "Mandela sentenced to life" },
      { year: "1990", event: "Mandela released; apartheid dismantled" },
      { year: "1994", event: "First democratic election; Mandela president" },
    ],
    "South Korea": [
      { year: "668", event: "Unified Silla Kingdom" },
      { year: "918", event: "Goryeo dynasty" },
      { year: "1392", event: "Joseon dynasty" },
      { year: "1910", event: "Japanese annexation" },
      { year: "1945", event: "Liberation; division at 38th parallel" },
      { year: "1948", event: "Republic of Korea established" },
      { year: "1950", event: "Korean War" },
      { year: "1953", event: "Armistice" },
      { year: "1961", event: "Park Chung-hee military coup" },
      { year: "1980", event: "Gwangju Uprising" },
      { year: "1987", event: "Democracy movement succeeds" },
      { year: "1988", event: "Seoul Olympics" },
      { year: "1997", event: "Asian financial crisis" },
    ],
    "South Sudan": [
      { year: "1899", event: "Anglo-Egyptian Sudan" },
      { year: "1955", event: "First Sudanese Civil War begins" },
      { year: "1983", event: "Second Sudanese Civil War" },
      { year: "2005", event: "Comprehensive Peace Agreement" },
      { year: "2011", event: "Independence (world's newest country)" },
      { year: "2013", event: "Civil war begins" },
      { year: "2018", event: "Peace agreement" },
    ],
    "Spain": [
      { year: "711", event: "Moorish conquest" },
      { year: "1492", event: "Reconquista completed; Columbus sails" },
      { year: "1519", event: "Conquest of Aztec Empire" },
      { year: "1532", event: "Conquest of Inca Empire" },
      { year: "1588", event: "Spanish Armada defeated" },
      { year: "1808", event: "Peninsular War (Napoleon)" },
      { year: "1898", event: "Spanish-American War (loses colonies)" },
      { year: "1936", event: "Spanish Civil War" },
      { year: "1939", event: "Franco dictatorship begins" },
      { year: "1975", event: "Franco dies; transition to democracy" },
      { year: "1978", event: "Democratic constitution" },
      { year: "1986", event: "Joins EC" },
    ],
    "Sri Lanka": [
      { year: "543 BC", event: "Sinhalese kingdom (traditional date)" },
      { year: "1505", event: "Portuguese arrival" },
      { year: "1658", event: "Dutch control" },
      { year: "1796", event: "British control" },
      { year: "1948", event: "Independence" },
      { year: "1983", event: "Civil war begins (Tamil Tigers)" },
      { year: "2004", event: "Indian Ocean tsunami" },
      { year: "2009", event: "Civil war ends" },
    ],
    "Sudan": [
      { year: "2500 BC", event: "Kingdom of Kush" },
      { year: "350", event: "Christian Nubian kingdoms" },
      { year: "1504", event: "Funj Sultanate" },
      { year: "1821", event: "Egyptian-Ottoman conquest" },
      { year: "1885", event: "Mahdist state" },
      { year: "1899", event: "Anglo-Egyptian Sudan" },
      { year: "1956", event: "Independence" },
      { year: "1983", event: "Second Civil War begins" },
      { year: "2003", event: "Darfur conflict" },
      { year: "2011", event: "South Sudan separates" },
      { year: "2019", event: "Al-Bashir overthrown" },
      { year: "2023", event: "RSF–Army civil war" },
    ],
    "Sweden": [
      { year: "800", event: "Viking Age" },
      { year: "1397", event: "Kalmar Union" },
      { year: "1523", event: "Gustav Vasa; independence from Denmark" },
      { year: "1611", event: "Swedish Empire era begins" },
      { year: "1700", event: "Great Northern War" },
      { year: "1814", event: "Last Swedish war (union with Norway)" },
      { year: "1995", event: "Joins EU" },
      { year: "2024", event: "Joins NATO" },
    ],
    "Switzerland": [
      { year: "1291", event: "Old Swiss Confederacy (founding cantons)" },
      { year: "1499", event: "De facto independence from HRE" },
      { year: "1648", event: "Independence recognized (Westphalia)" },
      { year: "1798", event: "Napoleonic invasion (Helvetic Republic)" },
      { year: "1815", event: "Permanent neutrality recognized" },
      { year: "1848", event: "Federal constitution" },
      { year: "1971", event: "Women's suffrage (national)" },
    ],
    "Syria": [
      { year: "3000 BC", event: "Ebla civilization" },
      { year: "333 BC", event: "Alexander's conquest" },
      { year: "636", event: "Arab conquest" },
      { year: "661", event: "Umayyad Caliphate capital at Damascus" },
      { year: "1516", event: "Ottoman rule" },
      { year: "1920", event: "French mandate" },
      { year: "1946", event: "Independence" },
      { year: "1967", event: "Six-Day War (loses Golan Heights)" },
      { year: "1970", event: "Assad dynasty begins" },
      { year: "2011", event: "Syrian Civil War begins" },
    ],
    "Taiwan": [
      { year: "1624", event: "Dutch colonization" },
      { year: "1662", event: "Koxinga expels Dutch" },
      { year: "1683", event: "Qing dynasty rule" },
      { year: "1895", event: "Japanese colony (after Sino-Japanese War)" },
      { year: "1945", event: "Japanese surrender; ROC takes control" },
      { year: "1949", event: "ROC government retreats to Taiwan" },
      { year: "1987", event: "Martial law lifted" },
      { year: "1996", event: "First democratic presidential election" },
    ],
    "Tanzania": [
      { year: "100", event: "Bantu migration" },
      { year: "800", event: "Swahili city-states (Kilwa)" },
      { year: "1498", event: "Portuguese arrival" },
      { year: "1885", event: "German East Africa" },
      { year: "1905", event: "Maji Maji Rebellion" },
      { year: "1919", event: "British mandate (WWI)" },
      { year: "1961", event: "Tanganyika independence" },
      { year: "1963", event: "Zanzibar independence" },
      { year: "1964", event: "Zanzibar Revolution; union as Tanzania" },
    ],
    "Thailand": [
      { year: "1238", event: "Sukhothai Kingdom" },
      { year: "1351", event: "Ayutthaya Kingdom" },
      { year: "1767", event: "Burmese sack Ayutthaya" },
      { year: "1782", event: "Chakri dynasty (Bangkok era)" },
      { year: "1932", event: "Revolution; constitutional monarchy" },
      { year: "1941", event: "Japanese occupation (WWII)" },
      { year: "1997", event: "Asian financial crisis" },
      { year: "2006", event: "Military coup" },
      { year: "2014", event: "Military coup" },
    ],
    "Timor-Leste": [
      { year: "1515", event: "Portuguese colonization" },
      { year: "1975", event: "Indonesian invasion" },
      { year: "1999", event: "Independence referendum; violence" },
      { year: "2002", event: "Independence" },
    ],
    "Tunisia": [
      { year: "814 BC", event: "Carthage founded" },
      { year: "146 BC", event: "Roman destruction of Carthage" },
      { year: "647", event: "Arab conquest" },
      { year: "1574", event: "Ottoman rule" },
      { year: "1881", event: "French protectorate" },
      { year: "1956", event: "Independence" },
      { year: "2011", event: "Jasmine Revolution (Arab Spring begins)" },
    ],
    "Turkey": [
      { year: "1071", event: "Battle of Manzikert (Seljuk Turks enter Anatolia)" },
      { year: "1299", event: "Ottoman Empire founded" },
      { year: "1453", event: "Constantinople falls" },
      { year: "1683", event: "Siege of Vienna (Ottoman decline begins)" },
      { year: "1914", event: "Enters World War I" },
      { year: "1915", event: "Armenian Genocide" },
      { year: "1919", event: "Turkish War of Independence" },
      { year: "1923", event: "Republic proclaimed (Atatürk)" },
      { year: "1952", event: "Joins NATO" },
      { year: "1974", event: "Invasion of Cyprus" },
      { year: "2016", event: "Failed coup attempt" },
    ],
    "Turkmenistan": [
      { year: "1881", event: "Russian conquest (Battle of Geok Tepe)" },
      { year: "1925", event: "Turkmen SSR" },
      { year: "1991", event: "Independence" },
      { year: "2006", event: "Niyazov dies; Berdimuhamedow era" },
    ],
    "Uganda": [
      { year: "1500", event: "Buganda Kingdom" },
      { year: "1894", event: "British protectorate" },
      { year: "1962", event: "Independence" },
      { year: "1971", event: "Idi Amin coup" },
      { year: "1979", event: "Amin ousted (Uganda-Tanzania War)" },
      { year: "1986", event: "Museveni takes power" },
    ],
    "Ukraine": [
      { year: "882", event: "Kyivan Rus" },
      { year: "1240", event: "Mongol destruction of Kyiv" },
      { year: "1648", event: "Cossack uprising (Khmelnytsky)" },
      { year: "1654", event: "Treaty of Pereyaslav (union with Russia)" },
      { year: "1876", event: "Ems Decree (ban on Ukrainian language)" },
      { year: "1918", event: "Ukrainian People's Republic" },
      { year: "1921", event: "Soviet control" },
      { year: "1932", event: "Holodomor (man-made famine)" },
      { year: "1941", event: "Nazi invasion; Holocaust" },
      { year: "1986", event: "Chernobyl disaster" },
      { year: "1991", event: "Independence from USSR" },
      { year: "2004", event: "Orange Revolution" },
      { year: "2014", event: "Revolution of Dignity; Russian annexation of Crimea" },
      { year: "2022", event: "Russian full-scale invasion" },
    ],
    "United Arab Emirates": [
      { year: "630", event: "Islam arrives" },
      { year: "1820", event: "Trucial States (British treaties)" },
      { year: "1958", event: "Oil discovered in Abu Dhabi" },
      { year: "1971", event: "Federation formed (independence)" },
      { year: "2010", event: "Burj Khalifa completed" },
    ],
    "United Kingdom": [
      { year: "43", event: "Roman conquest of Britain" },
      { year: "1066", event: "Norman Conquest" },
      { year: "1215", event: "Magna Carta" },
      { year: "1534", event: "English Reformation (Henry VIII)" },
      { year: "1588", event: "Defeat of Spanish Armada" },
      { year: "1642", event: "English Civil War" },
      { year: "1688", event: "Glorious Revolution" },
      { year: "1707", event: "Acts of Union (England & Scotland)" },
      { year: "1776", event: "American colonies declare independence" },
      { year: "1807", event: "Slave trade abolished" },
      { year: "1837", event: "Victorian era begins" },
      { year: "1914", event: "World War I" },
      { year: "1939", event: "World War II" },
      { year: "1945", event: "Post-war welfare state (NHS)" },
      { year: "1947", event: "Indian independence (decolonization era)" },
      { year: "1960", event: "African decolonization accelerates" },
      { year: "1973", event: "Joins EC" },
      { year: "2020", event: "Leaves EU (Brexit)" },
    ],
    "United States of America": [
      { year: "1492", event: "Columbus reaches Americas" },
      { year: "1607", event: "Jamestown (first permanent English settlement)" },
      { year: "1620", event: "Mayflower; Plymouth Colony" },
      { year: "1776", event: "Declaration of Independence" },
      { year: "1783", event: "Treaty of Paris (independence recognized)" },
      { year: "1787", event: "Constitution drafted" },
      { year: "1803", event: "Louisiana Purchase" },
      { year: "1812", event: "War of 1812" },
      { year: "1846", event: "Mexican-American War" },
      { year: "1861", event: "Civil War begins" },
      { year: "1865", event: "Civil War ends; slavery abolished" },
      { year: "1898", event: "Spanish-American War (colonial expansion)" },
      { year: "1917", event: "Enters World War I" },
      { year: "1929", event: "Great Depression begins" },
      { year: "1941", event: "Pearl Harbor; enters WWII" },
      { year: "1945", event: "Atomic bombs; WWII ends; UN founded" },
      { year: "1950", event: "Korean War" },
      { year: "1955", event: "Civil Rights Movement intensifies" },
      { year: "1963", event: "JFK assassinated" },
      { year: "1964", event: "Civil Rights Act" },
      { year: "1965", event: "Vietnam War escalation" },
      { year: "1969", event: "Moon landing" },
      { year: "1974", event: "Nixon resigns (Watergate)" },
      { year: "1991", event: "Gulf War; Cold War ends" },
      { year: "2001", event: "9/11 attacks; War on Terror" },
      { year: "2008", event: "Financial crisis; Obama elected" },
    ],
    "Uruguay": [
      { year: "1624", event: "Spanish settlement" },
      { year: "1811", event: "Revolution (Artigas)" },
      { year: "1828", event: "Independence (buffer state)" },
      { year: "1903", event: "Batlle reforms (welfare state)" },
      { year: "1973", event: "Military dictatorship" },
      { year: "1985", event: "Democracy restored" },
      { year: "2013", event: "Legalizes cannabis (first country)" },
    ],
    "Uzbekistan": [
      { year: "329 BC", event: "Alexander the Great conquers" },
      { year: "700", event: "Arab conquest" },
      { year: "1370", event: "Timur (Tamerlane) Empire" },
      { year: "1500", event: "Shaybanid Uzbek dynasty" },
      { year: "1865", event: "Russian conquest" },
      { year: "1924", event: "Uzbek SSR" },
      { year: "1991", event: "Independence" },
    ],
    "Venezuela": [
      { year: "1498", event: "Columbus arrives" },
      { year: "1522", event: "Spanish colonization" },
      { year: "1811", event: "Independence declared" },
      { year: "1821", event: "Battle of Carabobo (independence secured)" },
      { year: "1830", event: "Separates from Gran Colombia" },
      { year: "1914", event: "Oil discovered" },
      { year: "1958", event: "Democracy established" },
      { year: "1999", event: "Hugo Chávez elected" },
      { year: "2013", event: "Maduro succeeds Chávez" },
      { year: "2017", event: "Economic and humanitarian crisis" },
    ],
    "Vietnam": [
      { year: "111 BC", event: "Chinese domination begins" },
      { year: "938", event: "Independence from China (Ngô Quyền)" },
      { year: "1428", event: "Lê dynasty" },
      { year: "1858", event: "French colonization begins" },
      { year: "1940", event: "Japanese occupation" },
      { year: "1945", event: "Independence declared (Ho Chi Minh)" },
      { year: "1946", event: "First Indochina War (vs France)" },
      { year: "1954", event: "Dien Bien Phu; Geneva Accords; partition" },
      { year: "1955", event: "Vietnam War / Second Indochina War" },
      { year: "1968", event: "Tet Offensive" },
      { year: "1975", event: "Fall of Saigon; reunification" },
      { year: "1986", event: "Doi Moi economic reforms" },
    ],
    "Yemen": [
      { year: "1000 BC", event: "Kingdom of Saba (Sheba)" },
      { year: "630", event: "Islam arrives" },
      { year: "1839", event: "British take Aden" },
      { year: "1918", event: "North Yemen independent" },
      { year: "1967", event: "South Yemen independent" },
      { year: "1990", event: "Unification" },
      { year: "2015", event: "Civil war; Saudi-led intervention" },
    ],
    "Zambia": [
      { year: "1500", event: "Bantu migration" },
      { year: "1889", event: "British South Africa Company" },
      { year: "1924", event: "British protectorate (Northern Rhodesia)" },
      { year: "1964", event: "Independence (Kenneth Kaunda)" },
      { year: "1991", event: "Multi-party democracy" },
    ],
    "Zimbabwe": [
      { year: "1100", event: "Great Zimbabwe civilization" },
      { year: "1450", event: "Mutapa Empire" },
      { year: "1890", event: "British South Africa Company colonizes" },
      { year: "1965", event: "UDI (white minority Rhodesia)" },
      { year: "1972", event: "Bush War / Liberation War" },
      { year: "1980", event: "Independence (Mugabe)" },
      { year: "2000", event: "Land reform; economic crisis" },
      { year: "2008", event: "Hyperinflation crisis" },
      { year: "2017", event: "Mugabe ousted" },
    ],
  };