import type { WaterLabel } from "./types";

export const waterLabels: WaterLabel[] = [
  { name: "Pacific Ocean", lat: 0, lng: -128, size: 6, minZ: 1 },
  { name: "Atlantic Ocean", lat: 15, lng: -35, size: 6, minZ: 1 },
  { name: "Indian Ocean", lat: -20, lng: 75, size: 6, minZ: 1 },
  { name: "Southern Ocean", lat: -65, lng: 0, size: 5, minZ: 1 },
  { name: "Arctic Ocean", lat: 78, lng: 0, size: 5, minZ: 1 },
  { name: "Caribbean Sea", lat: 15, lng: -75, size: 5, minZ: 2 },
  { name: "Mediterranean Sea", lat: 35, lng: 18, size: 4.5, minZ: 2 },
  { name: "South China Sea", lat: 12, lng: 115, size: 5, minZ: 2 },
  { name: "Arabian Sea", lat: 14, lng: 65, size: 5, minZ: 2 },
  { name: "Bay of Bengal", lat: 14, lng: 88, size: 5, minZ: 2 },
  { name: "Gulf of Mexico", lat: 25, lng: -90, size: 4.5, minZ: 2 },
  { name: "Coral Sea", lat: -18, lng: 155, size: 5, minZ: 2 },
  { name: "Tasman Sea", lat: -38, lng: 162, size: 5, minZ: 2 },
  { name: "Bering Sea", lat: 57, lng: -175, size: 5, minZ: 2 },
  { name: "Sea of Japan", lat: 40, lng: 135, size: 4.5, minZ: 3 },
  { name: "North Sea", lat: 57, lng: 3, size: 4, minZ: 3 },
  { name: "Baltic Sea", lat: 58, lng: 20, size: 4, minZ: 3 },
  { name: "Black Sea", lat: 43, lng: 35, size: 4, minZ: 3 },
  { name: "Red Sea", lat: 20, lng: 38, size: 4, minZ: 3 },
  { name: "Persian Gulf", lat: 26, lng: 52, size: 3.5, minZ: 4 },
  { name: "Hudson Bay", lat: 60, lng: -85, size: 5, minZ: 2 },
  { name: "Sea of Okhotsk", lat: 55, lng: 150, size: 4.5, minZ: 3 },
  { name: "Philippine Sea", lat: 20, lng: 132, size: 5, minZ: 2 },
  { name: "Mozambique Channel", lat: -18, lng: 42, size: 3.5, minZ: 4 },
  { name: "Gulf of Guinea", lat: 2, lng: 2, size: 4.5, minZ: 2 },
  { name: "Scotia Sea", lat: -57, lng: -45, size: 5, minZ: 2 },
  { name: "Labrador Sea", lat: 57, lng: -55, size: 4.5, minZ: 3 },
  { name: "Norwegian Sea", lat: 67, lng: 2, size: 4.5, minZ: 3 },
  { name: "Greenland Sea", lat: 74, lng: -10, size: 4.5, minZ: 3 },
  { name: "Caspian Sea", lat: 41, lng: 51, size: 3.5, minZ: 4 },
];
